version: '3.0'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nignx.conf
      - ./nginx/server:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
  postgres:
    image: postgres
    restart: always
    environment:
    # Change the default password to whatever you want
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  mongo:
    image: mongo
    restart: always
    environment:
    # Change the default user and password to whatever you want
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/dbs:/data/db
      - ./mongo/logs:/var/log/mongodb
