version: '3.1'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /docker_volumes/ngnix/conf/nignx.conf:/etc/ngnix.conf
      - /docker_volumes/ngnix/server:/usr/share/nginx/html
      # - ./nginx/conf/nginx.conf:/etc/nignx.conf
      # - ./nginx/server:/usr/share/nginx/html
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /docker_volumes/postgresql/date:/var/lib/postgresql/data
      # - ./containers_data/postgresql/data:/var/lib/postgresql/data
      # - /home/vagrant/psql:/var/lib/postgresql/data
    # user: "1000:1000"
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"
    volumes:
      - /docker_volumes/mongo/data:/data/db
      # - ./mongo/data:/data/db
      # - /home/vagrant/mongo:/data/db
    # user: "1000:1000"
